package com.github.duync.jmeterviewer;

import org.apache.jmeter.control.Controller;
import org.apache.jmeter.gui.tree.JMeterTreeNode;
import org.apache.jmeter.samplers.Sampler;
import org.apache.jmeter.testelement.TestElement;

final class JMeterTreeTextExporter {
    private JMeterTreeTextExporter() {
    }

    static String names(JMeterTreeNode root) {
        StringBuilder builder = new StringBuilder();
        appendNames(root, builder);
        return builder.toString();
    }

    static String outline(JMeterTreeNode root) {
        StringBuilder builder = new StringBuilder();
        appendOutline(root, builder, 0);
        return builder.toString();
    }

    static String codeOutline(JMeterTreeNode root) {
        StringBuilder builder = new StringBuilder();
        builder.append("// JMeter tree outline generated by the JetBrains plugin\n");
        appendCode(root, builder, 0);
        return builder.toString();
    }

    private static void appendNames(JMeterTreeNode node, StringBuilder builder) {
        TestElement element = node.getTestElement();
        if (element instanceof Sampler || element instanceof Controller) {
            builder.append(node.getName()).append('\n');
        }
        for (int i = 0; i < node.getChildCount(); i++) {
            appendNames((JMeterTreeNode) node.getChildAt(i), builder);
        }
    }

    private static void appendOutline(JMeterTreeNode node, StringBuilder builder, int depth) {
        indent(builder, depth);
        builder.append(node.getName())
                .append(" [")
                .append(node.getTestElement().getClass().getSimpleName())
                .append("]")
                .append(node.isEnabled() ? "" : " disabled")
                .append('\n');
        for (int i = 0; i < node.getChildCount(); i++) {
            appendOutline((JMeterTreeNode) node.getChildAt(i), builder, depth + 1);
        }
    }

    private static void appendCode(JMeterTreeNode node, StringBuilder builder, int depth) {
        indent(builder, depth);
        builder.append("element(\"")
                .append(escape(node.getName()))
                .append("\", \"")
                .append(node.getTestElement().getClass().getName())
                .append("\")");
        if (node.getChildCount() == 0) {
            builder.append('\n');
            return;
        }
        builder.append(" {\n");
        for (int i = 0; i < node.getChildCount(); i++) {
            appendCode((JMeterTreeNode) node.getChildAt(i), builder, depth + 1);
        }
        indent(builder, depth);
        builder.append("}\n");
    }

    private static void indent(StringBuilder builder, int depth) {
        for (int i = 0; i < depth; i++) {
            builder.append("  ");
        }
    }

    private static String escape(String value) {
        return value == null ? "" : value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
